preset: recommended

finder:
  exclude:
    - "lib"

disabled:
  - align_double_arrow
  - concat_without_spaces
  - new_with_braces
  - no_blank_lines_after_phpdoc
  - no_spaces_inside_offset
  - phpdoc_no_package
  - phpdoc_summary
  - simplified_null_return
  - trim_array_spaces

enabled:
  - concat_with_spaces
  - declare_strict_types
  - dir_constant
  - is_null
  - linebreak_after_opening_tag
  - modernize_types_casting
  - no_empty_comment
  - no_php4_constructor
  - no_short_echo_tag
  - no_useless_else
  - not_operator_with_successor_space
  - php_unit_construct
  - php_unit_dedicate_assert
  - phpdoc_link_to_see
  - phpdoc_property
  - phpdoc_return_self_reference
  - pow_to_exponentiation
  - random_api_migration
  - return_type_declaration
  - semicolon_after_instruction
  - single_line_class_definition
  - strict_comparison
  - strict_param
  - ternary_to_null_coalescing
  - unalign_double_arrow
